spring:
  application:
    name: user

server:
  port: 8888
  
say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8091,localhost:8092,localhost:8093
    ServerListRefreshInterval: 15000